image: cypress/browsers:node14.16.0-chrome92-ff89

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install

cypress_tests:
  stage: test
  script:
    - npx cypress install
    - npm run finaltest-allure
  artifacts:
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/
      - allure-report/
